const cocktailData = {
    coctelesClasicos: [
        { nombre: "Alexander", imagen: "../images/alexander.jpg", ingredientes: ["1 oz Cogñac", "1 oz Licor de Cacao", "1 oz Half and Half"], receta: "En una coctelera con hielo, agrega el coñac, el licor de cacao y el Half and Half.\n Agita vigorosamente durante 15-20 segundos para enfriar y mezclar bien los ingredientes.\n Cuela la mezcla en una Copa Martini o Copa Coupé, previamente enfriada.\n Decorar con una ramita de canela y espolvorear un poco de cacao en polvo por encima.\n ¡Disfruta!" },
        { nombre: "Americano", imagen: "../images/americano.jpg", ingredientes: ["30 ml de Campari", "30 ml de Vermouth Rosso", "Chorrito de Soda"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Barracuda", imagen: "../images/barracuda.jpg", ingredientes: ["45 ml de Ron Blanco", "15 ml de Licor de Banana", "30 ml de Zumo de Ananá", "60 ml de Champagne"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Bee's Knees", imagen: "../images/beesknees.jpg", ingredientes: ["50 ml de Gin", "25 ml de Zumo de Limón", "25 ml de Jugo de Naranja", "2 Cucharaditas de Miel"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Between the Sheets", imagen: "../images/betweenthesheets.jpg", ingredientes: ["30 ml de Ron", "30 ml de Cognac", "30 ml de Triple Sec", "30 ml de Zumo de Limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Black Russian", imagen: "../images/blackrussian.jpg", ingredientes: ["45 ml de Vodka", "45 ml de Licor de Café", "30 ml de Café (opcional)"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Bloody Mary", imagen: "../images/bloodymary.jpg", ingredientes: ["45 ml de Vodka", "90 ml de Jugo de Tomate", "15 ml de Zumo Limón", "1 Pizca de Sal Fina", "1 Pizca de Pimienta Negra", "1-3 Gotas de Salsa Picante (como Tabasco)"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Boulevardier", imagen: "../images/boulevardier.jpg", ingredientes: ["45 ml de Whisky", "30 ml de Campari", "30 ml de Vermouth rosso"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Caipirinha", imagen: "../images/caipirinha.jpg", ingredientes: ["75 ml de Cachaca", "30 ml de Almibar", "Lima"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Cosmopolitan", imagen: "../images/cosmopolitan.jpg", ingredientes: ["45 ml de Vodka", "15 ml de Triple Sec", "30 ml de Jugo de Arándano rojo", "15 ml Zumo de Limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Cuba Libre", imagen: "../images/cubalibre.jpg", ingredientes: ["45 ml de Ron Blanco", "120 ml de Coca-Cola", "10 ml de Zumo de Limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Daiquiri Clásico", imagen: "../images/daiquiriclasico.jpg", ingredientes: ["60 ml de Ron Blanco", "30 ml de Zumo de Limón", "20 ml de Almíbar"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Dry Martini", imagen: "../images/drymartini.jpg", ingredientes:["75 ml de Gin", "15 ml de Vermouth Dry", "Dos o tres Aceitunas"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Espresso Martini", imagen: "../images/espressomartini.jpg", ingredientes:["45 ml de Vodka", "30 ml de Licor de Café", "30 ml de Café Espresso", "15 ml de Almíbar"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Gancia Batido", imagen: "../images/ganciabatido.jpg", ingredientes: ["75 ml de Gancia", "30 ml de Almibar", "Limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Grasshopper", imagen: "../images/grasshopper.jpg", ingredientes: ["30 ml de Vodka", "30 ml de Licor de Chocolate Blanco", "15 ml de Licor de Menta", "15 ml de Half and Half"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Hanky Panky", imagen: "../images/hankypanky.jpg", ingredientes: ["45 ml de London Dry Gin", "45 ml de Vermouth Rosso", "10 ml Fernet Branca"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Long Island Iced Tea", imagen: "../images/longislandicedtea.jpg", ingredientes: ["15 ml de Vodka", "15 ml de Ron", "15 ml de Gin", "15 ml de Triple Sec, 30 ml de Sweet & Sour", "Coca-Cola"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Mai-Tai Clásico", imagen: "../images/maitaiclasico.jpg", ingredientes:["45 ml de Ron Blanco", "15 ml de RonOscuro", "15 ml de Amaretto", "15 ml de Triple Sec", "10 ml de Almíbar", "30 ml de Zumo de Limón"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Manhattan", imagen: "../images/manhattan.jpg", ingredientes:["60 ml de Whisky canadian", "30 ml de Vermouth Rosso", "Gotas de Bitter Angostura"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Margarita", imagen: "../images/margarita.jpg", ingredientes:["60 ml de Tequila", "45 ml de Triple Sec", "45 ml de Sour Mix"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Martinez", imagen: "../images/martinez.jpg", ingredientes: ["45 ml de London Dry Gin", "45 ml de Vermouth Rosso", "5 ml de Marrasquino", "3 gotas de Bitter Angostura"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Mary Pickford", imagen: "../images/marypickford.jpg", ingredientes: ["45 ml de Ron Blanco", "45 ml de Zumo de Piña", "10 ml de Marrasquino", "5 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Mimosa Clásico", imagen: "../images/mimosaclasico.jpg", ingredientes: ["75 ml de Champagne", "75 ml de Zumo de Naranja"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Mint Julep", imagen: "../images/mintjulep.jpg", ingredientes: ["60 ml de Bourbon", "8-10 Hojas de Menta frezca", "10 ml de Almíbar"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Moscow Mule", imagen: "../images/moscowmule.jpg", ingredientes: ["60 ml de Vodka", "120 ml de Cerveza de Jengibre", "15 ml de Zumo de Lima"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Mojito", imagen: "../images/mojito.jpg", ingredientes:["60 ml de Ron", "30 ml de Sour Mix", "6-8 hojas de Menta", "Soda"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Negroni", imagen: "../images/negroni.jpg", ingredientes:["30 ml de Gin", "30 ml de Vermouth Rosso", "30 ml de Campari"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "New York Sour", imagen: "../images/newyorksour.jpg", ingredientes: ["60 ml de Bourbon o Whisky", "30 ml de Zumo de Limón", "20 ml de Almibar", "Clara de Huevo", "15 ml de Vino Tinto (como Merlot o Cabernet Sauvignon)"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Old Cuban", imagen: "../images/oldcuban.jpg", ingredientes: ["45 ml de Ron Añejo", "6-8 Hojas de Menta", "30 ml de Zumo de Limón", "20 ml de Almibar", "2 Gotas de Bitter Angostura", "60 ml de Champagne"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Old Fashioned", imagen: "../images/oldfashioned.jpg", ingredientes:["105 ml de Bourbon", "Una cucharada de Azúcar", "Gotas de Bitter Angostura"], receta: "Ingredientes y pasos para el Martini..." },
        { nombre: "Penicillin", imagen: "../images/penicillin.jpg", ingredientes: ["60 ml de Whisky scoth", "20 ml de Syrup de Gengibre", "20 ml de Syrup de Miel", "30 ml de Zumo de limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Sex on the Beach", imagen: "../images/sexonthebeach.jpg", ingredientes: ["45 ml de Vodka", "30 ml de Licor de Durazno", "75 ml de Jugo de Naranja", "10 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Tequila Sunrise", imagen: "../images/tequilasunrise.jpg", ingredientes: ["45 ml de Tequila", "90 ml de Jugo de Naranja", "10 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Whiskey Sour", imagen: "../images/whiskeysour.jpg", ingredientes: ["45 ml de Whisky", "30 ml de Zumo de Lima", "20 ml de Almibar Simple", "Clara de Huevo"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "White Lady", imagen: "../images/whitelady.jpg", ingredientes: ["40 ml de Gin", "30 ml de Triple Sec", "20 ml de Zumo de Limón"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "White Russian", imagen: "../images/whiterussian.jpg", ingredientes: ["30 ml de Vodka", "45 ml de Licor de Café", "30 ml de Half and Half", "30 ml de Café (opcional)"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Zombie Clásico", imagen: "../images/zombieclasico.jpg", ingredientes: ["45 ml de Ron Oscuro", "45 ml de Ron Dorado", "20 ml de Zumo de Limón", "15 ml de Falernum", "10 ml de Granadina", "2 gotas de Bitter Angostura"], receta: "Ingredientes y pasos para la Margarita..." },
        // { nombre: "", imagen: "../images/.jpg", ingredientes: [], receta: "Ingredientes y pasos para la Margarita..." },
    ],
    coctelesBatidos: [
        { nombre: "Blue Hawaiian", imagen: "../images/bluehawaiian.jpg", ingredientes: ["30 ml de Ron", "15 ml de Blue Curacao", "60 ml de Pulpa de Ananá", "45 ml de Sour Mix"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Chacho", imagen: "../images/chacho.jpg", ingredientes: ["30 ml de Whisky", "45 ml de Licor de Choclote", "15 ml de Licor de Huevo"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Cielito Lindo", imagen: "../images/cielitolindo.jpg", ingredientes: ["45 ml de Vodka", "90 ml de Piña Colada", "15 ml de Blue Curacao"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Extasis", imagen: "../images/extasis.jpg", ingredientes: ["20 ml de Licor de Kiwi", "20 ml de Licor Durazno", "20 ml de Licor de Frutilla", "20 ml de Licor de Banana", "30 ml de Piña Colada", "30 ml de Pulpa de Ananá"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Kriptonita", imagen: "../images/kriptonita.jpg", ingredientes: ["45 ml de Vodka", "90 ml de Piña Colada", "15 ml de Licor de Menta"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Maddy", imagen: "../images/maddy.jpg", ingredientes: ["45 ml de Ron", "15 ml de Licor de Cassis", "30 ml de Jugo de Manzana", "45 ml de Pulpa de Ananá"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Orgasmo", imagen: "../images/orgasmo.jpg", ingredientes: ["45 ml de Vodka", "30 ml de Licor de Durazno", "60 ml de Piña Colada", "15 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Pearl Harbor", imagen: "../images/pearlharbor.jpg", ingredientes: ["30 ml de Vodka, ", "30 ml de Licor de Melón", "90 ml de Pulpa de Ananá"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Primavera", imagen: "../images/primavera.jpg", ingredientes: ["45 ml de Vodka", "30 ml de Jugo de Naranja", "30 ml de Jugo de Pomelo", "30 ml de Pulpa de Ananá", "15 ml de Pulpa de Frutilla"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Samantha", imagen: "../images/samantha.jpg", ingredientes: ["45 ml de Vodka", "30 ml de Licor de Banana", "60 ml de Piña Colada", "15 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Screaming Orgasm", imagen: "../images/screamingorgasm.jpg", ingredientes: ["30 ml de Ron", "30 ml de Bailey's", "30 ml de Amaretto", "30 ml de Licor de Café", "30 ml de Half and Half", "Garnish de Crema"], receta: "Ingredientes y pasos para la Margarita..." },
        //{ nombre: "", imagen: "../images/.jpg", ingredientes: [], receta: "Ingredientes y pasos para la Margarita..." },
    ],
    coctelesRefrescados: [],
    coctelesFrozzen: [],
    coctelesTikis: [],
    coctelesChampagne: [],
    cafeteria: [
        { nombre: "Café de la Montaña", imagen: "../images/cafemontaña.jpg", ingredientes: ["30 ml de Licor de Chocolate", "30 ml de Licor de Chocolate Blanco", "150 ml de Café Espresso", "20% de Crema Batida"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Café Belga", imagen: "../images/cafebelga.jpg", ingredientes: ["30 ml de Bailey's", "30 ml de Triple Sec", "150 ml de Café Espresso", "20% de Crema Batida"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Café Francés", imagen: "../images/cafefrances.jpg", ingredientes: ["60 ml de Brandy o Cognac", "150 ml de Café Espresso", "20% Crema Batida"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Café Irlandés", imagen: "../images/cafeirlandes.jpg", ingredientes: ["60 ml de Whisky", "150 ml de Café Espresso", "20% de Crema Batida"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Café Marroc", imagen: "../images/cafemarroc.jpg", ingredientes: ["30 ml de Licor de Dulce de Leche", "60 ml de Leche caliente", "120 ml de Café Espresso", "20% Crema Batida"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Coco Mocha", imagen: "../images/cocomocha.jpg", ingredientes: ["30 ml de Licor de Coco", "30 ml de Triple Sec", "30 ml de Café frío"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Iced Coffee", imagen: "../images/icedcoffee.jpg", ingredientes: ["30 ml de Ron", "30 ml de Licor de Vainilla", "90 ml de Leche fría", "2 cucharaditas de Café Instantáneo"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Margarita Coffee", imagen: "../images/margaritacoffee.jpg", ingredientes: ["30 ml de Tequila", "30 ml de Triple Sec", "45 ml de Café Espresso"], receta: "Ingredientes y pasos para la Margarita..." },
        //{ nombre: "", imagen: "../images/.jpg", ingredientes: [], receta: "Ingredientes y pasos para la Margarita..." },
    ],
    shooters: [],
    coctelesAutor: [
        { nombre: "A.P Zombie", imagen: "../images/apzombie.jpg", ingredientes:["30 ml de Ron oscuro", "45 ml de Amaretto (casero)", "30 ml de Falernum (casero)", "30 ml de Jugo de Pomelo", "30 ml de Zumo de Limón", "15 ml de Granadina"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Bubba Loo", imagen: "../images/bubbaloo.jpg", ingredientes: ["60 ml de Vermouth rosso", "30 ml de almibar", "30 ml de zumo de limón", "30 ml de Jugo de Blueberry", "Clara de Huevo"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Cofferula", imagen: "../images/cofferula.jpg", ingredientes: ["30 ml de Ron oscuro", "30 ml de Licor de Café", "30 ml de Amarula", "30 ml de Café Espresso"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Marroquino", imagen: "../images/marroquino.jpg", ingredientes: ["45 ml de Whisky scotch", "15 ml de Licor de Café", "15 ml de Amaretto (casero)", "30 ml de Licor de Marroc (casero)", "30 ml de Syrup de Marroc", "30 ml de Half and Half"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Ocaso de Sol", imagen: "../images/ocasodesol.jpg", ingredientes: ["30 ml de Aperol", "30 ml de Gancia", "30 ml de Granadina", "Rellenar con Naranja"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Pink Ilex", imagen: "../images/pinkilex.jpg", ingredientes:["30 ml de London Dry Gin", "45 ml de Gancia", "30 ml de Infusión de Yerba Mate", "30 ml de Falernum (casero)", "30 ml de Jugo de Pomelo", "1 cucharada chica de Miel"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Red Ilex", imagen: "../images/redilex.jpg", ingredientes: ["30 ml de Gin", "30 ml de Aperol", "30 ml de Falernum (casero)", "30 ml de Infusión de Yerba Mate", "30 ml de Jugo de Naranja"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "Rose of the Nile", imagen: "../images/roseofthenile.jpg", ingredientes: ["60 ml de Vermouth rosso", "30 ml de Syrup de Jengibre", "30 ml de zumo de Limón", "30 ml de Jugo de Pomelo", "Clara de Huevo"], receta: "Ingredientes y pasos para la Margarita..." },
        { nombre: "White Ilex", imagen: "../images/whiteilex.jpg", ingredientes: ["45 ml de Ginebra", "30 ml de Falernum (Casero)", "30 ml de Infusión de Yerba Mate", "30 ml de Pulpa de Ananá"], receta: "Ingredientes y pasos para la Margarita..." },
        // { nombre: "", imagen: "../images/.jpg", ingredientes: [], receta: "Ingredientes y pasos para la Margarita..." },
    ]
};

//export default cocktailData;
window.cocktailData = cocktailData;